# Generated by Django 3.1 on 2020-10-27 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OrderTiles',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Person_name', models.CharField(max_length=50)),
                ('Order_Tiles_name', models.CharField(max_length=50)),
                ('Order_Tiles_size', models.CharField(max_length=20)),
                ('Order_Tiles_type', models.CharField(max_length=40)),
                ('Order_Tiles_rate', models.IntegerField(default=0)),
                ('Order_Tiles_Quantity', models.CharField(max_length=100)),
                ('Order_Tiles_Time', models.DateTimeField(auto_now_add=True)),
                ('Order_image', models.ImageField(upload_to='shop/images')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Tiles_name', models.CharField(max_length=50)),
                ('Tiles_size', models.CharField(max_length=20)),
                ('Tiles_type', models.CharField(blank=True, choices=[('kitchen', 'kitchen'), ('bathroom', ' bathroom'), ('room', 'room')], max_length=40)),
                ('Tiles_desc', models.CharField(max_length=100)),
                ('Tiles_rate', models.IntegerField(default=0)),
                ('image', models.ImageField(upload_to='shop/images')),
            ],
        ),
    ]
