# Generated by Django 3.1 on 2020-10-27 14:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Shop', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ordertiles',
            name='Order_Tiles_Time',
        ),
    ]
