# Generated by Django 3.1 on 2020-10-27 17:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Shop', '0004_auto_20201027_2104'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordertiles',
            name='Person',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='product',
            name='Tiles_type',
            field=models.CharField(blank=True, choices=[('kitchen', 'kitchen'), ('bathroom', ' bathroom'), ('room', 'room')], max_length=50),
        ),
    ]
