# Generated by Django 3.1 on 2020-10-27 17:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Shop', '0005_auto_20201027_2242'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordertiles',
            name='Person',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ordertiles', to=settings.AUTH_USER_MODEL),
        ),
    ]
