# Generated by Django 3.1 on 2020-10-30 16:53

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Shop', '0006_auto_20201027_2258'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordertiles',
            name='Person_mobile_address',
            field=models.CharField(default=django.utils.timezone.now, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ordertiles',
            name='Person_mobile_number',
            field=models.CharField(default=django.utils.timezone.now, max_length=10),
            preserve_default=False,
        ),
    ]
