# Generated by Django 3.1 on 2020-10-30 17:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Shop', '0007_auto_20201030_2223'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ordertiles',
            old_name='Person_mobile_address',
            new_name='Person_address',
        ),
    ]
